# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dockerimg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerimg',
            name='imgdid',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
